<a href="https://colab.research.google.com/github/Nuthana1234/Calibo_assignment_practice/blob/main/NuthanaSree_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SECTION-A**


1.   NumPy arrays are preferred over Python lists because they store data in contiguous memory blocks and use a single, uniform data type.
2.   Vectorization is the process of performing mathematical operations on entire arrays at once, entirely eliminating explicit for-loops in Python.


1. A * B (Element-wise Multiplication): Multiplies corresponding elements of arrays A and B. The arrays must have the exact same shape.
 A @ B (Matrix Multiplication / Dot Product): Performs standard linear algebra matrix multiplication where row elements of A are multiplied by column elements of B and summed. The inner dimensions must match.
2. Broadcasting is a mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes without making unnecessary, memory-expensive copies of the data in memory.


1. flatten(): Always returns a copy of the original array collapsed into a single dimension. Modifying a flattened array does not alter the original data.ravel(): Returns a flattened, contiguous 1D view of the original array whenever possible without allocating new memory. Modifying a raveled array will modify the original data.



1. axis=0 (Column-wise): The operation collapses the rows. It moves down the columns, calculating a result for each column.
  axis=1 (Row-wise): The operation collapses the columns. It moves across the rows, calculating a result for each row.
  
  Code:

import numpy as np

arr = np.array([[1, 2],
                [3, 4]])

print(np.sum(arr, axis=0))  # Output: [4, 6]

print(np.sum(arr, axis=1))  # Output: [3, 7]


7.  It is important to scale numerical features because machine learning models that rely on distance metrics are highly sensitive to the scale of data.
If one feature has a much larger range than another, it will dominate the model's updates and distance calculations, leading to poor performance and slow convergence.
8.   np.mean() with NaN: Returns NaN. One missing value breaks the entire calculation.
  np.nanmean(): Ignores NaN values and correctly averages only the remaining numbers.


1.  Extension: The (samples, features) layout expands to (samples, height, width, channels).
  
    Exact Shape: (64, 128, 128, 3) (64 images, 128x128 pixels, 3 color channels).

2.   Importance: Ensures your results stay identical across runs so you can reliably test and debug model changes.
np.random.default_rng(seed): Forces the random number generator to produce the exact same sequence every time, locking down random variation.


  














# **SECTION-B**

**Questions**
B1.Predict the exact output and/or resulting shape. Justify in one sentence. [2 marks]​

a = np.array([1, 2, 3])​

b = np.array([[1], [2], [3]])​

print((a + b).shape)​

​

B2. Predict the output and/or shape. [2 marks]​

x = np.arange(1, 7).reshape(2, 3)​

print(x[:, 1])​

​

B3. Predict the output and/or shape. [2 marks]​

arr = np.array([5, 10, 15, 20, 25])​

print(arr[arr % 10 == 0])​

​

B4. Predict the output and/or shape. [2 marks]​

m = np.array([[1, 2], [3, 4]])​

print(m.T @ m)​

B5. Predict the output and/or shape. [2 marks]​

data = np.array([1, 2, np.nan, 4])​

print(np.mean(data), np.nanmean(data))​

​

B6. Predict the output and/or shape. [2 marks]​

x = np.array([10, 20, 30])​

y = np.where(x > 15, 1, 0)​

print(y)​

​

B7. Predict the output and/or shape. [2 marks]​

a = np.zeros((3, 4))​

print(a.ndim, a.size)​

​

B8. Predict the output and/or shape. [2 marks]​

arr = np.arange(1, 13).reshape(3, 4)​

print(arr[::-1, ::-1])​

#**Answers**
import numpy as np

# ============================================================
# B1. Broadcasting
# ============================================================
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

print("B1:")
print((a + b).shape)

Output: (3, 3)


# ============================================================
# B2. Column slicing
# ============================================================
x = np.arange(1, 7).reshape(2, 3)

print("\nB2:")
print(x)
print(x[:, 1])
Output:

[[1 2 3]
[4 5 6]]
[2 5]


# ============================================================
# B3. Boolean indexing
# ============================================================
arr = np.array([5, 10, 15, 20, 25])

print("\nB3:")
print(arr[arr % 10 == 0])
Output: [10 20]


# ============================================================
# B4. Transpose + Matrix multiplication
# ============================================================
m = np.array([[1, 2], [3, 4]])

print("\nB4:")
print(m.T @ m)
Output:
 [[10 14]
   [14 20]]


# ============================================================
# B5. mean() vs nanmean()
# ============================================================
data = np.array([1, 2, np.nan, 4])

print("\nB5:")
print(np.mean(data), np.nanmean(data))


Output:
mean()    -> NaN affects the result
nanmean() -> ignores NaN


# ============================================================
# B6. np.where()
# ============================================================
x = np.array([10, 20, 30])

y = np.where(x > 15, 1, 0)

print("\nB6:")
print(y)

Output: [0 1 1]


# ============================================================
# B7. ndim and size
# ============================================================
a = np.zeros((3, 4))

print("\nB7:")
print(a.ndim, a.size)


 Output: 2 12

ndim = number of dimensions
size = total number of elements


# ============================================================
# B8. Reverse rows and columns
# ============================================================
arr = np.arange(1, 13).reshape(3, 4)

print("\nB8:")
print(arr)
print(arr[::-1, ::-1])

Output:
[[12 11 10  9]
[ 8  7  6  5]
[ 4  3  2  1]]

# **SECTION-C**

1.Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40). [5 marks]​

In [6]:
import numpy as np
scores = np.array([35, 42, 89, 21, 40, 55])
labels = np.where(scores >= 40, 'P', 'F')
print("Results")
print(labels)


Results
['F' 'P' 'P' 'F' 'P' 'P']


2.Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy. [5
marks]​

In [4]:
import numpy as np

def standardize(x):
    return (x - np.mean(x)) / np.std(x)
data = np.array([10, 20, 30, 40, 50])
print(standardize(data))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


3.Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an
appropriate NumPy stacking function and print the resulting shape. [5 marks]​

In [5]:
import numpy as np
batch1 = np.random.rand(10, 4)
batch2 = np.random.rand(15, 4)
combined_batches = np.vstack((batch1, batch2))
print("Resulting shape:", combined_batches.shape)



Resulting shape: (25, 4)


4.Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized
expression. [5 marks]​

In [ ]:
import numpy as np

# Generate dummy matrix X with shape (100, 5)
X = np.random.rand(100, 5)

# Vectorized standardization along columns (axis=0)
X_standardized = (X - np.mean(X, axis=0)) / np.std(X, axis=0)

print("Standardized shape:", X_standardized.shape)


5.Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true. [5 marks]​

In [10]:
import numpy as np
# Feature matrix
X = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5]
])
# Weight vector
w = np.array([2, 3])
# Bias
b = 1
# True values
y_true = np.array([9, 14, 19, 24])
# Prediction
y_pred = X @ w + b
# Mean Squared Error
mse = np.mean((y_true - y_pred) ** 2)
print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [ 9 14 19 24]
MSE: 0.0


6.Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the
shape and confirm identical results with the same seed. [5 marks]​

In [13]:
import numpy as np
# First generator
rng1 = np.random.default_rng(42)
data1 = rng1.normal(size=(10, 3))
# Second generator with the same seed
rng2 = np.random.default_rng(42)
data2 = rng2.normal(size=(10, 3))
print("Shape:", data1.shape)
print("Data:")
print(data1)
print("\nIdentical results:", np.array_equal(data1, data2))

Shape: (10, 3)
Data:
[[ 0.30471708 -1.03998411  0.7504512 ]
 [ 0.94056472 -1.95103519 -1.30217951]
 [ 0.1278404  -0.31624259 -0.01680116]
 [-0.85304393  0.87939797  0.77779194]
 [ 0.0660307   1.12724121  0.46750934]
 [-0.85929246  0.36875078 -0.9588826 ]
 [ 0.8784503  -0.04992591 -0.18486236]
 [-0.68092954  1.22254134 -0.15452948]
 [-0.42832782 -0.35213355  0.53230919]
 [ 0.36544406  0.41273261  0.430821  ]]

Identical results: True


7.Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max
normalization. [5 marks]​

In [12]:
import numpy as np
# Sample grayscale image
image = np.array([
    [0, 50, 100],
    [150, 200, 255]
])
# Min-max normalization
image_normalized = (image - image.min()) / (image.max() - image.min())
print("Original image:")
print(image)
print("\nNormalized image:")
print(image_normalized)

Original image:
[[  0  50 100]
 [150 200 255]]

Normalized image:
[[0.         0.19607843 0.39215686]
 [0.58823529 0.78431373 1.        ]]


8.Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across
height, width and channels. State the axis argument and why. [5 marks]

In [14]:
import numpy as np

# 4 RGB images
images = np.random.default_rng(42).random((4, 28, 28, 3))

# Average pixel value of each image
average_values = np.mean(images, axis=(1, 2, 3))

print("Shape:", average_values.shape)
print("Average pixel values:")
print(average_values)

Shape: (4,)
Average pixel values:
[0.49879444 0.49546077 0.48993754 0.50644914]


# **SECTION-D**

1.You are given a raw 1D or 2D NumPy array containing NaN values.​

Describe, step by step, the NumPy operations you would apply to:​

(a) detect missing values,​

(b) handle them appropriately and justify your strategy, and​

(c) normalize or standardize the clean data before it is fed to a model.​

​

Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.​

In [17]:
import numpy as np
#Sample 2D array containing NaN values
data = np.array([
    [10.0, 20.0, np.nan],
    [30.0, 40.0, 50.0],
    [60.0, np.nan, 80.0]
])
#Detect missing values
missing_values = np.isnan(data)
print("Missing values:")
print(missing_values)
print("Number of NaN values:", np.isnan(data).sum())
#Handle missing values using mean imputation
mean_value = np.nanmean(data)
data_clean = np.nan_to_num(data, nan=mean_value)
print("\nMean used for imputation:", mean_value)
print("Clean data:")
print(data_clean)
# Min-max normalization
data_normalized = (
    (data_clean - data_clean.min()) /
    (data_clean.max() - data_clean.min())
)

print("\nNormalized data:")
print(data_normalized)

Missing values:
[[False False  True]
 [False False False]
 [False  True False]]
Number of NaN values: 2

Mean used for imputation: 41.42857142857143
Clean data:
[[10.         20.         41.42857143]
 [30.         40.         50.        ]
 [60.         41.42857143 80.        ]]

Normalized data:
[[0.         0.14285714 0.44897959]
 [0.28571429 0.42857143 0.57142857]
 [0.71428571 0.44897959 1.        ]]


D2

Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.​

​

Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.​

​

Compute the average image of the batch, meaning the element-wise mean across all 16 images.​

​

State the shape of your result and explain why.​

In [18]:
import numpy as np

# Create batch of 16 RGB images
rng = np.random.default_rng(42)
images = rng.integers(0, 256, size=(16, 64, 64, 3))

# Average across the 16 images
average_image = np.mean(images, axis=0)

print("Original batch shape:", images.shape)
print("Average image shape:", average_image.shape)

Original batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


The following code contains more than one bug:​

​

X = np.array([[1, 2],​

[2, 3],​

[3, 4]]) # shape (3, 2)​

w = np.array([0.5, 1.0, 0.2]) # intended weight vector​

b = 2.0​

y_pred = X @ w + b​

y_true = np.array([10, 20, 30])​

mse = np.mean(y_true - y_pred ** 2)​

​

Identify every bug. Explain, in terms of shapes and operator precedence, why each is a problem, and rewrite the corrected code.​

In [19]:
import numpy as np

X = np.array([
    [1, 2],
    [2, 3],
    [3, 4]
])  # shape (3, 2)

# 2 features → 2 weights
w = np.array([0.5, 1.0])  # shape (2,)

b = 2.0

# Predictions
y_pred = X @ w + b

y_true = np.array([10, 20, 30])

# Mean Squared Error
mse = np.mean((y_true - y_pred) ** 2)

print("X shape:", X.shape)
print("w shape:", w.shape)
print("y_pred:", y_pred)
print("MSE:", mse)

X shape: (3, 2)
w shape: (2,)
y_pred: [4.5 6.  7.5]
MSE: 244.16666666666666


# **SECTION-E**

E1. Per-Column Min–Max Normalization [5 marks]​

Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global
min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns.​

In [20]:
import numpy as np

X = np.array([
    [10, 100, 1000],
    [20, 200, 2000],
    [30, 300, 3000],
    [40, 400, 4000]
])

# Per-column minimum and maximum
X_min = X.min(axis=0)
X_max = X.max(axis=0)

# Per-column Min-Max normalization
X_normalized = (X - X_min) / (X_max - X_min)

print("Original matrix:")
print(X)

print("\nNormalized matrix:")
print(X_normalized)

Original matrix:
[[  10  100 1000]
 [  20  200 2000]
 [  30  300 3000]
 [  40  400 4000]]

Normalized matrix:
[[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]


E2. Three-Level Score Classification [5 marks]​

Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each
score as:​

Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).​

Hint: You may need to nest or combine np.where() calls.​

In [23]:
import numpy as np

scores = np.array([25, 40, 55, 70, 85, 95])

result = np.where(
    scores < 40,
    "Fail",
    np.where(scores <= 70, "Average", "Excellent")
)
print("Result")
print(result)

Result
['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']
