<a href="https://colab.research.google.com/github/Nuthana1234/Calibo_assignment_practice/blob/main/NuthanaSree_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Section-A



**Q1**.Array Operations and Vectorization



[20 40 60]



0 20



1 40



2 60



dtype: int64


Both NumPy arrays and Pandas Series support vectorized operations, meaning the multiplication is applied to every element.




**Q2**.Boolean Filtering



Student Marks



1 B 80



2 C 65



3 D 90



**Explanation**: Boolean filtering is used to filter the data based on condition given in the question.




**Q3**.Descriptive Statistics



30.0



50



30.0



**Explanation**: mean() function returns the average value, max() function returns the maximum value, median() returns the middle value of the array after sorting it.

**Q4**.Group-wise Analysis

Department



HR    40000.0


IT    50000.0


Name: Salary, dtype: float64

groupby():

Groups rows according to Department.
Selects the Salary column.
Calculates the mean salary for each department.




**Q5**. Pandas Correlation — Positive

import pandas as pd


df = pd.DataFrame({
    
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

output

1.0


**Explanation**: The coefficient 1.0 indicates a perfect positive linear relationship. As study hours increase, marks also increase.


**Q6**.Pandas Correlation — Negative

import pandas as pd

df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

print(df['Price'].corr(df['Demand']))


Output

-1.0

**Explanation**: The coefficient 1.0 indicates a perfect positive linear relationship. As study hours increase, marks also increase.






#**Section-B**

Q1. JSON and CSV

Issue: header=None tells Pandas that the CSV has no header, so the first row is treated as data.

In [4]:
import pandas as pd
df = pd.read_csv("/content/Students.csv")
print(df)


,ID,Name,Date,Unnamed: 3,Marks
0,101,"Asha,R",9/1/2026,NaN,80.0
1,102,Ravi,1/9/2026,NaN,NaN
2,103,Neha,9/3/2026,NaN,NaN


Q2. Data Analysis​


Issue: sort_values('Salary') sorts in ascending order by default, so .head(5) gives the five lowest salaries.

In [11]:
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary', ascending=False).head(5))

  Employee  Salary
5        F   70000
3        D   60000
1        B   50000
4        E   45000
0        A   30000


Explanation: ascending=False sorts salaries from highest to lowest, so head(5) returns the five highest salaries.

Q3. Cleaning Data

Issue: fillna() returns a modified Series but does not automatically update the original DataFrame.

In [12]:
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print(df)

   Marks
0   70.0
1   80.0
2   90.0


Explanation: The missing value is replaced with the column mean, and the result is assigned back to df['Marks'].

4. Correlation

Issue: DataFrame.corr() does not take column names as positional arguments in this way.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

1.0


Explanation: Select the two Series and use .corr() to calculate their correlation.

#**Section-C**

Q1. NumPy Broadcasting

In [2]:
import numpy as np
a = np.array([[10], [20], [30]])
b = np.array([[1, 2, 3]])
result = a + b
print(result)
print(result.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


Explanation: Broadcasting expands the smaller dimensions so the arrays can be added element-wise.

If b = np.array([1, 2]), a broadcasting error occurs because the dimensions are incompatible.

Q2. CSV Parsing

In [5]:
import pandas as pd

df = pd.read_csv("Students.csv", na_values=["", "NA"])

df["Date"] = pd.to_datetime(
    df["Date"],
    dayfirst=True,
    errors="coerce"
)

print(df)
print(df.dtypes)

    ID    Name       Date  Unnamed: 3  Marks
0  101  Asha,R 2026-01-09         NaN   80.0
1  102    Ravi 2026-09-01         NaN    NaN
2  103    Neha 2026-03-09         NaN    NaN
ID                     int64
Name                  object
Date          datetime64[ns]
Unnamed: 3           float64
Marks                float64
dtype: object


Explanation: na_values handles specified missing-value markers, while pd.to_datetime() converts the Date column to datetime format.

Q3. Extreme Salary

In [6]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})

print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())

Mean: 2522500.0
Median: 32500.0


The extreme salary of 10,000,000 significantly increases the mean. The median is less affected and better represents the typical salary in this dataset.

The record should be investigated before removing it because the extreme value may be genuine or may indicate a data-entry error

#**Section-D**

Q1. Cleaning Sequence

In [10]:
import pandas as pd
df = pd.read_csv("/content/student_assessment_dirty.csv")

# Inspect
print(df.head())
df.info()
print(df.isnull().sum())
# Standardize departments
df["Department"] = (
    df["Department"]
    .str.strip()
    .str.upper()
    .str.replace(".", "", regex=False)
)
# Remove exact duplicates
before = len(df)
df = df.drop_duplicates()
records_removed = before - len(df)
# Convert marks to numeric
df["Marks"] = (
    df["Marks"]
    .astype("string")
    .str.extract(r"(\d+(?:\.\d+)?)")[0]
)

df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

# Identify missing marks
missing_marks = df["Marks"].isna().sum()

# Identify invalid marks
invalid_marks = df[
    df["Marks"].notna() &
    ~df["Marks"].between(0, 100)
]

df
print("Records removed:", records_removed)
print("Missing marks:", missing_marks)
print("Invalid marks:")
print(invalid_marks)

  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha       I.T.     Python      92
3       S104        Karan         HR     Python     NaN
4       S105        Meera         HR     Python  Absent
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Student_ID    15 non-null     object
 1   Student_Name  15 non-null     object
 2   Department    15 non-null     object
 3   Assessment    15 non-null     object
 4   Marks         12 non-null     object
dtypes: object(5)
memory usage: 732.0+ bytes
Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           3
dtype: int64
Records removed: 1
Missing marks: 4
Invalid marks:
   Student_ID Student_Name Department Assessment  Marks
14       S114